export const allEvents = ['ETHGlobal Prague', 'ETHGlobal Taipei', 'ETHGlobal Trifecta - Trusted Execution Environments', 'ETHGlobal Trifecta - Zero Knowledge', 'ETHGlobal Trifecta - Agents', 'Agentic Ethereum', 'ETHGlobal Bangkok', 'ETHGlobal San Francisco', 'ETHGlobal Singapore', 'ETHOnline 2024', 'Superhack 2024', 'Scaling Ethereum 2024', 'ETHGlobal Sydney', 'ETHGlobal Brussels', 'StarkHack', 'HackFS 2024', 'Frameworks', 'ETHGlobal London', 'LFGHO', 'Circuit Breaker', 'ETHIndia 2023', 'ETHOnline 2023', 'ETHGlobal Istanbul', 'HackFS 2023', 'Scaling Ethereum 2023', 'ETHGlobal New York', 'Superhack', 'ETHGlobal Paris', 'Autonomous Worlds', 'ETHGlobal Lisbon', 'ETHGlobal Waterloo', 'ETHIndia 2022', 'ETHGlobal Tokyo', 'FVM Space Warp', 'Hack FEVM', 'ETHSanFrancisco 2022', 'ETHBogotá', 'ETHOnline 2022', 'ETHMexico', 'Metabolism', 'HackFS 2022', 'ETHNewYork 2022', 'ETHAmsterdam', 'DAOHacks', 'LFGrow', 'BuildQuest', 'Road to Web3', 'NFTHack 2022', 'Web3Jam', 'UniCode', 'ETHOnline 2021', 'HackFS 2021', 'HackMoney 2021', 'Web3 Weekend', 'Scaling Ethereum', 'MarketMake', 'NFTHack', 'ETHOnline', 'HackFS', 'HackMoney']

export const allPrizes = [
    "0x",
    "0xPARC",
    "1inch",
    "API3",
    "Aave",
    "Aave Grants DAO",
    "Airdao",
    "Airdao",
    "Airstack",
    "Alchemy",
    "Aleo",
    "Alliance",
    "Alluo",
    "ApeCoin",
    "Aragon",
    "Arbitrum",
    "Argent",
    "Arx",
    "Autonomy",
    "Avail",
    "Axelar",
    "Axiom",
    "Aztec",
    "Bacalhau",
    "Base",
    "Biconomy",
    "BitDSM",
    "Bitkub",
    "Blockless",
    "Blockscout",
    "Boba Network",
    "Brevis",
    "Bunzz",
    "Capsule",
    "Cartesi",
    "Cartridge",
    "Celestia",
    "Celo",
    "Ceramic",
    "Certora",
    "Chainlink",
    "Chainsafe",
    "Chiliz",
    "Chronicle Protocol",
    "Circle",
    "Circles",
    "CoW Protocol",
    "Coinbase Cloud",
    "Coinbase Developer Platform",
    "Cometh",
    "Compound Grants Program",
    "Conduit",
    "Connext",
    "Consensus Lab",
    "CoopHive",
    "Covalent",
    "Cronos",
    "Curvegrid",
    "DELV",
    "DIMO",
    "DataverseOS",
    "Dfns",
    "Dune",
    "Dynamic",
    "ENS",
    "EY Blockchain",
    "Element Finance",
    "Empiric",
    "Envio",
    "Essential",
    "Estuary",
    "Ethereum Attestation Service",
    "Ethereum Foundation",
    "Etherspot",
    "Euler",
    "Evmos",
    "Family",
    "Farcaster",
    "Fhenix",
    "Filecoin",
    "Finalist",
    "Findora",
    "Flare Network",
    "Flashbots",
    "Fleek",
    "Flow",
    "Fluence",
    "Fraxtal",
    "Fuel",
    "Gaia",
    "Galadriel",
    "Gearbox",
    "Gelato Network",
    "Gnosis",
    "Gnosis Chain",
    "Goldsky",
    "Hedera",
    "Herodotus",
    "Highlight",
    "Huddle01",
    "Hyperbolic",
    "Hyperlane",
    "Hyperlane",
    "IPFS",
    "Inco Network",
    "Intmax",
    "Iron Fish",
    "Karma3Labs",
    "Kinto",
    "Lattice",
    "LayerZero",
    "Ledger",
    "Lens Protocol",
    "Li.Fi",
    "Lighthouse",
    "Lilypad",
    "Liquity",
    "Lit Protocol",
    "Livepeer",
    "MakerDAO",
    "Mantle",
    "Marlin",
    "MetaMask",
    "MetaMask",
    "Metal L2",
    "Midpoint",
    "Mina Protocol",
    "Mode Network",
    "Mona",
    "Moonbeam",
    "Morph",
    "Morpho Labs",
    "NEAR Protocol",
    "NETH",
    "NFT.Storage",
    "Neon EVM",
    "Nethermind",
    "Next.ID",
    "Nillion",
    "NounsDAO",
    "OKX Web3",
    "Oasis Protocol",
    "Okto",
    "OpenSea",
    "Openmesh Network",
    "Optimism",
    "POAP",
    "PancakeSwap",
    "Phala Network",
    "Pinata",
    "Polybase",
    "Polygon",
    "Powerloom",
    "Privacy + Scaling Explorations",
    "Privy",
    "Push Protocol",
    "Pyth Network",
    "Quantstamp",
    "QuickNode",
    "Reazon Holdings",
    "Revise",
    "Ripio",
    "Risc Zero",
    "Rome Protocol",
    "Rootstock",
    "Router",
    "SKALE Network",
    "SSV Network",
    "SSV Network",
    "Safe",
    "Saturn",
    "Scroll",
    "Secured Finance",
    "Shardeum",
    "Sign Protocol",
    "Sindri",
    "Sismo",
    "Spheron",
    "Squid Router",
    "StackOS",
    "Stackr Labs",
    "Starknet",
    "Starknet",
    "Starton",
    "Story Protocol",
    "Streamr Network",
    "Sunscreen",
    "Superfluid",
    "Superform",
    "Tableland",
    "Taiko",
    "Tellor",
    "Tenderly",
    "The Graph",
    "Threshold Network",
    "Token Flow",
    "Tokenbound",
    "Triangle",
    "UMA",
    "UNICEF Innovation",
    "UNLIMIT",
    "Uniswap Foundation",
    "Unknown",
    "Unlock Protocol",
    "Valist",
    "Vara",
    "Venn",
    "Voyager",
    "Waku",
    "WalletConnect",
    "Walrus",
    "WeatherXM",
    "Web3Auth",
    "Witness",
    "Worldcoin",
    "Wormhole",
    "XDC Foundation",
    "XMTP",
    "Zerion",
    "ZetaChain",
    "Zircuit",
    "Zondax",
    "Zora",
    "dabl.club",
    "drand",
    "frames.js",
    "libp2p",
    "thirdweb",
    "unshETH.xyz",
    "vlayer Labs",
    "zkBob",
    "zkSync"
];

export const eventDisplayNames: { [key: string]: string } = {
    'ETHGlobal Prague': 'Prague \'25',
    'ETHGlobal Taipei': 'Taipei \'25',
    'ETHGlobal Trifecta - Trusted Execution Environments': 'Trifecta - TEE',
    'ETHGlobal Trifecta - Zero Knowledge': 'Trifecta - ZK',
    'ETHGlobal Trifecta - Agents': 'Trifecta - Agents',
    'Agentic Ethereum': 'Agentic Ethereum',
    'ETHGlobal Bangkok': 'Bangkok \'24',
    'ETHGlobal San Francisco': 'SF \'24',
    'ETHGlobal Singapore': 'Singapore \'24',
    'ETHOnline 2024': 'ETHOnline \'24',
    'Superhack 2024': 'Superhack \'24',
    'ETHGlobal Brussels': 'Brussels \'24',
    'ETHGlobal Sydney': 'Sydney \'24',
    'Scaling Ethereum 2024': 'Scaling Ethereum \'24',
    'ETHGlobal London': 'London \'24',
    'ETHIndia 2023': 'India \'23',
    'ETHGlobal Istanbul': 'Istanbul \'23',
    'ETHOnline 2023': 'ETHOnline \'23',
    'ETHGlobal New York': 'NYC \'23',
    'Superhack': 'Superhack \'23',
    'ETHGlobal Paris': 'Paris \'23',
    'ETHGlobal Waterloo': 'Waterloo \'23',
    'ETHGlobal Lisbon': 'Lisbon \'23',
    'ETHGlobal Tokyo': 'Tokyo \'23',
    'Scaling Ethereum 2023': 'Scaling Ethereum \'23',
    'ETHSanFrancisco 2022': 'SF \'22',
  };